<#
	.SYNOPSIS
		The purpose of get a copy of the WVU Foundation's address book.
		It will be used to import into the HSC address book.

	.PARAMETER WVUFAddressBookFile
		The output file generated by the program. It should not be
		changed from the default without also changing the value
		in the import file.

	.NOTES
		Written by: Jeff Brusoe
		Last Updated: January 6, 2021
#>

[CmdletBinding()]
param (
	[ValidateNotNullOrEmpty()]
	[string]$WVUFAddressBookFile = "$PSScriptRoot\Logs\" +
									(Get-Date -Format yyyy-MM-dd) +
									"-WVUFAddressBook.csv"
)

#Configure environment
try {
	Set-HSCEnvironment -ErrorAction Stop

	Write-Output "Connecting to WVUFoundation Tenant"
	Connect-WVUFoundationExchangeOnline -ErrorAction Stop
	
	New-Item $WVUFAddressBookFile -Type file -Force -ErrorAction Stop
}
catch {
	Write-Warning "Unable to configure environment"
	Invoke-HSCExitCommand -ErrorCount $Error.Count
}

try {
	Write-Output "Generating list of WVUF Mailboxes"
	$WVUFRecipients = Get-Recipient -identity "*" -Resultsize Unlimited |
		Where-Object {$_.PrimarySMTPAddress -like "*@wvuf.org*"}
}
catch {
	Write-Warning "Unable to generate list of WVUF Recipients"
	Invoke-HSCExitCommand -ErrorCount $Error.Count
}

foreach ($WVUFRecipient in $WVUFRecipients)
{
	Write-Output $("WVUF Alias: " + $WVUFRecipient.Alias)
	Write-Output $("WVUF Primary SMTP Address: " + $WVUFRecipient.PrimarySMTPAddress)

	if (([string]::IsNullOrEmpty($WVUFRecipient.LastName)) -OR
		([string]::IsNullOrEmpty($WVUFRecipient.FirstName)))
	{
		#Skip if first or last name is missing
		
		if ([string]::IsNullOrEmpty($WVUFRecipient.LastName)) {
			Write-Output "Skipping mailbox because of missing last name"
		}
		else {
			Write-Output "Skipping mailbox because of missing last name"
		}
	}
	elseif ($WVUFRecipient.DisplayName.toLower().IndexOf("test") -ge 0) {
		Write-Output "Test account - Skipping"
	}
	elseif ($WVUFRecipient.PrimarySMTPAddress -like "*onmicrosoft.com*") {
		Write-Output "Invalid primary SMTP address. Account is not being imported."
	}
	else {
		$PrimarySMTPAddress = $WVUFRecipient.PrimarySMTPAddress
		Write-Output "Primary SMTP Address: $PrimarySMTPAddress"

		$Properties = @(
			"DisplayName",
			"FirstName",
			"LastName",
			"Title",
			"Department",
			"Phone",
			"PrimarySMTPAddress",
			"Alias",
			"WhenChanged",
			"HiddenFromAddressListsEnabled"
		)

		$WVUFRecipient |
			Select-Object -Property $Properties |
			Export-Csv $WVUFAddressBookFile -Append -NoTypeInformation
	}

	Write-Output "**************************"
}

Invoke-HSCExitCommand -ErrorCount $Error.Count